### ISSUE TITLE
no internet, what to check ?

### ISSUE THREAD

**Issue by softlion** [freifunkMUC/wg-access-server-chart#21]
Hello :)

I setup this helm chart on my k8s cluster on a dedicated hosted computer.

I am able to get into the web ui, configure it, then connect my windows PC to that wireguard server.

But, then, I cant ping or even traceroute any website. It's like I have no connection at all.

What I did:
- set 1.1.1.1 as the DNS server in the client config
- route only IPV4 (remove ipv6 ::0/0)
- from inside the wireguard pod, I verifed that I can ping and curl google.com

logLevel is set to trace.

**Comment by GoliathLabs** [comment]
what's the output from traceroute or tcpdump? How do you route your traffic?
