### ISSUE TITLE
Empty gh-pages

### ISSUE THREAD

**Issue by catrielmuller** [freifunkMUC/wg-access-server-chart#6]
@awlx can you add me to the organization of this repo.

To fix the CI you need create an empty gh-page branch and configure github pages to use them.

```bash
git switch --orphan gh-pages
git push -u origin gh-pages
git commit --allow-empty -m "GH-Pages Branch"
git push -u origin gh-pages
```

**Comment by GoliathLabs** [comment]
@catrielmuller I've already fixed the issue

**Comment by GoliathLabs** [comment]
But it would be nice to have you on board. I think you will be added to the wg-access-server-chart team shortly.
