### ISSUE TITLE
Only run the workflow on release

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/wg-access-server-chart#7]
If the push to main is done without changing the release version, the workflow fails. My question is if it is more practical to run the workflow only when a version of the chart is released

**Comment by GoliathLabs** [comment]
What do you think @catrielmuller

**Comment by ggwpp** [comment]
We can do release same way (by merging to main branch). I'll help create another workflow to make sure contributor bumping chart version before we merge the PR.

WDYT ?

**Comment by ggwpp** [comment]
I have pull-request for that here https://github.com/freifunkMUC/wg-access-server-chart/pull/11
Please let me know what do you think.

**Comment by GoliathLabs** [comment]
Thanks! Merged 😄
