### ISSUE TITLE
Rename value postgres to storage

### ISSUE THREAD

**Issue by elcomtik** [freifunkMUC/wg-access-server-chart#9]
I think we should refactor the key name for [postgresql](https://github.com/freifunkMUC/wg-access-server-chart/blob/main/charts/wg-access-server/values.yaml#L47), however, its value is used in deployment env variable [WG_STORAGE](https://github.com/freifunkMUC/wg-access-server-chart/blob/main/charts/wg-access-server/templates/deployment.yaml#L85). 

This env available could be used to configure MySQL connection string as well. I propose to rename it to storage.

We may add some mapping between the old and new names to maintain backward compatibility and introduce a deprecation warning until removed in the next major release. Another option is to rename it because the chart is still in version 0.x.x. I would personally prefer the last one.

**Comment by GoliathLabs** [comment]
I would also opt for the latter, since the chart is still in alpha stage. Feel free to open a PR with the corresponding changes 👍🏼

**Comment by elcomtik** [comment]
Going to work on it imediately.
